# HTTP: ACME challenge + redirect to HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name artist-insight-api.taonity.org;

    include conf.d/include/letsencrypt-acme-challenge.conf;

    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS: reverse proxy
server {
    server_name artist-insight-api.taonity.org;

    include conf.d/include/tls.conf;
    include conf.d/include/security-headers.conf;
    include conf.d/include/block-exploits.conf;

    location / {
        include conf.d/include/proxy.conf;
        set $upstream http://artist-insight-service-prod-app:8080;
        proxy_pass $upstream;
    }
}
