version: '2.4'

services:
  prodenv-loki:
    image: grafana/loki:2.7.1
    ports:
      - 3100:3100
    volumes:
      - ./config.yaml:/etc/loki/config.yaml
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - loki

networks:
  loki: