services:
  certbot:
    image: infinityofspace/certbot_dns_duckdns:v1.6
    volumes:
      - ./../data/certbot/letsencrypt:/etc/letsencrypt
      - ./../data/certbot/www:/var/www/certbot
      - ./letsencrypt:/var/log/letsencrypt
      - ./duckdns.ini:/duckdns.ini
    entrypoint: "/bin/sh -c 'certbot renew'"