services:
  certbot:
    image: certbot/dns-cloudflare:v5.6.0
    restart: "no"
    volumes:
      - ./../data/certbot/letsencrypt:/etc/letsencrypt
      - ./../data/certbot/www:/var/www/certbot
      - ./letsencrypt:/var/log/letsencrypt
      - ./cloudflare.ini:/cloudflare.ini:ro
    entrypoint: "/bin/sh -c 'certbot renew'"