services:
  db:
    restart: unless-stopped
    ports:
      - 5434:5432

  flyway:
    restart: "no"

  app:
    restart: unless-stopped

  frontend:
    restart: unless-stopped
    ports:
      - 127.0.0.1:3002:3000