---
server:
  http_listen_port: 3100
#  log_level: debug

schema_config:
  configs:
    - from: 2021-08-01
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h
common:
  path_prefix: /loki
  replication_factor: 1
  storage:
    s3:
      endpoint: prodenv-minio:9000
      insecure: true  
      bucketnames: loki-data
      access_key_id: loki
      secret_access_key: supersecret
      s3forcepathstyle: true
  ring:
    kvstore:
      store: memberlist
ruler:
  storage:
    s3:
      bucketnames: loki-ruler

ingester:
  chunk_idle_period: 1m

# table_manager:
#   retention_deletes_enabled: true
#   retention_period: 10m

compactor:
  retention_enabled: true
  retention_delete_delay: 1m
  delete_request_cancel_period: 1m

limits_config:
  retention_period: 48h

