---
server:
  http_listen_port: 3100
  # log_level: debug

schema_config:
  configs:
    - from: 2021-08-01
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h
    - from: "2025-02-24" # <---- A date in the future
      index:
        period: 24h
        prefix: index_tsdb_
      object_store: s3
      schema: v11
      store: tsdb

common:
  path_prefix: /loki
  replication_factor: 1
  storage:
    s3:
      endpoint: minio:9000
      insecure: true  
      bucketnames: loki-data
      access_key_id: ${MINIO_ACCESS_KEY}
      secret_access_key: ${MINIO_ROOT_PASSWORD}
      s3forcepathstyle: true
  ring:
    kvstore:
      store: memberlist
ruler:
  storage:
    s3:
      bucketnames: loki-ruler

ingester:
  chunk_idle_period: 30m

# table_manager:
#   retention_deletes_enabled: true
#   retention_period: 10m

compactor:
  retention_enabled: true
  retention_delete_delay: 2h
  delete_request_cancel_period: 24m

limits_config:
  retention_period: 30d
  split_queries_by_interval: 24h


frontend:
  max_outstanding_per_tenant: 4096

querier:
  max_concurrent: 4096

query_scheduler:
  max_outstanding_requests_per_tenant: 4096
