version: '2.4'

services:
  restore-backup:
    image: generaltao725/command-runner:0.1.0
    environment:
      - COMMAND_RUNNER_GROUP=prodenv
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock:ro
      - ./shared:/etc/runner/scripts/shared:ro
      - backup-data:/archive:ro

      - mc-data:/backup/mc-data
      - java-discord-help-bot-volume-db:/backup/java-discord-help-bot-volume-db
