version: '2.4'

services:

  prodenv-docker-webhook:
    extends:
      file: docker-webhook/docker-compose.yml
      service: prodenv-docker-webhook

  prodenv-jenkins-dind:
    extends:
      file: jenkins-dind/docker-compose.yml
      service: prodenv-jenkins-dind

  prodenv-jenkins:
    extends:
      file: jenkins/docker-compose.yml
      service: prodenv-jenkins
    depends_on:
      prodenv-jenkins-dind:
        condition: service_healthy

  prodenv-loki:
    extends:
      file: loki/docker-compose.yml
      service: prodenv-loki
    depends_on:
      prodenv-minio:
        condition: service_healthy

  prodenv-promtail:
    extends:
      file: promtail/docker-compose.yml
      service: prodenv-promtail
    depends_on:
      prodenv-loki:
        condition: service_healthy

  prodenv-minio:
    extends:
      file: minio/docker-compose.yml
      service: prodenv-minio

  prodenv-mc:
    extends:
      file: mc/docker-compose.yml
      service: prodenv-mc
    depends_on:
      prodenv-minio:
        condition: service_healthy

  prodenv-grafana:
    extends:
      file: grafana/docker-compose.yml
      service: prodenv-grafana
    depends_on:
      prodenv-loki:
        condition: service_healthy
      prodenv-promtail:
        condition: service_started
  
  prodenv-docker-volume-backup:
    extends:
      file: docker-volume-backup/docker-compose.yml
      service: prodenv-docker-volume-backup

  prodenv-test:
    extends:
      file: test/docker-compose.yml
      service: prodenv-test

  prodenv-restore-backup:
    extends:
      file: restore-backup/docker-compose.yml
      service: prodenv-restore-backup
    depends_on:
      prodenv-mc:
        condition: service_started

volumes:
  prodenv-docker-volume-backup-data:
  prodenv-jenkins-data:
  prodenv-minio-data:
  prodenv-minio-mirror-data:
  java-discord-help-bot-volume-db:
  br:
  prodenv-mc-data:

networks:
  jenkins:
  loki-network:
