version: '2.4'

services:

  webhook:
    extends:
      file: cicd/docker-webhook/docker-compose.yml
      service: docker-webhook

  loki:
    extends:
      file: logging/loki/docker-compose.yml
      service: loki
    depends_on:
      minio:
        condition: service_healthy

  promtail:
    extends:
      file: logging/promtail/docker-compose.yml
      service: promtail
    depends_on:
      loki:
        condition: service_healthy

  minio:
    extends:
      file: logging/minio/docker-compose.yml
      service: minio

  mc:
    extends:
      file: logging/mc/docker-compose.yml
      service: mc
    depends_on:
      minio:
        condition: service_healthy

  grafana:
    extends:
      file: logging/grafana/docker-compose.yml
      service: grafana
    depends_on:
      loki:
        condition: service_healthy
      promtail:
        condition: service_started
  
  make-backup:
    extends:
      file: backup/make-backup/docker-compose.yml
      service: make-backup
    depends_on:
      minio:
        condition: service_healthy
      mc:
        condition: service_started

  restore-backup:
    extends:
      file: backup/restore-backup/docker-compose.yml
      service: restore-backup
    depends_on:
      mc:
        condition: service_started

  portainer:
    extends:
      file: portainer/docker-compose.yml
      service: portainer

volumes:
  backup-data:
  minio-data:
  minio-mirror-data:
  java-discord-help-bot-volume-db:
  mc-data:
  portainer_data:

