services:

  docker-webhook:
    extends:
      file: cicd/docker-webhook/docker-compose.yml
      service: docker-webhook
    networks:
     - nginx

  loki:
    extends:
      file: logging/loki/docker-compose.yml
      service: loki
    networks:
     - logging
    depends_on:
      minio:
        condition: service_healthy

  promtail:
    extends:
      file: logging/promtail/docker-compose.yml
      service: promtail
    networks:
     - logging
    depends_on:
      loki:
        condition: service_healthy

  minio:
    extends:
      file: logging/minio/docker-compose.yml
      service: minio
    networks:
     - logging

  mc:
    extends:
      file: logging/mc/docker-compose.yml
      service: mc
    networks:
     - logging
    depends_on:
      minio:
        condition: service_healthy
  
  node-exporter:
    extends:
      file: logging/node-exporter/docker-compose.yml
      service: node-exporter
    networks:
     - logging
  
  prometheus:
    extends:
      file: logging/prometheus/docker-compose.yml
      service: prometheus
    networks:
     - logging
     - artist-insight-shared
    depends_on:
      node-exporter:
        condition: service_started

  grafana-curl:
    extends:
      file: logging/grafana/curl/docker-compose.yml
      service: grafana-curl

  grafana:
    extends:
      file: logging/grafana/docker-compose.yml
      service: grafana
    networks:
     - logging
     - nginx
    depends_on:
      loki:
        condition: service_healthy
      promtail:
        condition: service_started
      prometheus:
        condition: service_started
      grafana-curl:
        condition: service_completed_successfully
        
  make-backup:
    extends:
      file: backup/make-backup/docker-compose.yml
      service: make-backup
    depends_on:
      minio:
        condition: service_healthy
      mc:
        condition: service_started

  restore-backup:
    extends:
      file: backup/restore-backup/docker-compose.yml
      service: restore-backup
    depends_on:
      mc:
        condition: service_started

  portainer:
    extends:
      file: portainer/docker-compose.yml
      service: portainer
    networks:
     - nginx
     
  nginx:
    extends:
      file: nginx/nginx/docker-compose.yml
      service: nginx
    networks:
     - nginx
     - prodenv-shared-internal
  certbot:
    extends:
      file: nginx/certbot/docker-compose.yml
      service: certbot
 
volumes:
  backup-data:
  minio-data:
  minio-mirror-data:
  mc-data:
  portainer-data:
  nginx-proxy-manager-data:
  prometheus_data:

networks:
  nginx:
  logging:
  prodenv-shared-internal:
    external: true
  artist-insight-shared:
    external: true