version: '2.4'

services:

  prodenv-docker-webhook:
    extends:
      file: docker-webhook/docker-compose.yml
      service: prodenv-docker-webhook

  prodenv-jenkins-dind:
    extends:
      file: jenkins-dind/docker-compose.yml
      service: prodenv-jenkins-dind

  prodenv-jenkins:
    extends:
      file: jenkins/docker-compose.yml
      service: prodenv-jenkins
    depends_on:
      prodenv-jenkins-dind:
        condition: service_healthy

  prodenv-loki:
    extends:
      file: loki/docker-compose.yml
      service: prodenv-loki
    depends_on:
      prodenv-minio:
        condition: service_healthy

  prodenv-promtail:
    extends:
      file: promtail/docker-compose.yml
      service: prodenv-promtail
    depends_on:
      prodenv-loki:
        condition: service_healthy

  prodenv-minio:
    extends:
      file: minio/docker-compose.yml
      service: prodenv-minio

  prodenv-grafana:
    extends:
      file: grafana/docker-compose.yml
      service: prodenv-grafana
    depends_on:
      prodenv-loki:
        condition: service_healthy
      prodenv-promtail:
        condition: service_started

volumes:
  prodenv-jenkins-data:
  prodenv-minio-data:

networks:
  jenkins:
  loki: