services:
  grafana:
    image: grafana/grafana:11.6.16
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.taonity.org
      - GF_SERVER_DOMAIN=grafana.taonity.org
      - GF_INSTALL_PLUGINS=grafana-lokiexplore-app 1.0.37
      - GF_PLUGINS_PREINSTALL_DISABLED=true
      - GF_PLUGINS_PLUGIN_ADMIN_ENABLED=false
    volumes:
      - ./provisioning:/etc/grafana/provisioning
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
