version: '2.4'

services:
   docker-webhook:
    image: generaltao725/docker-webhook:0.4.0
    ports: 
     - "9000:9000"
    volumes: 
      - ./shared:/etc/webhook/shared
      - //etc/webhook/cache:/etc/webhook/cache
      - //var/run/docker.sock:/var/run/docker.sock
    env_file:
     - ../.env
    environment:
     - "DOCKER_USERNAME=generaltao725"
      