version: '2.4'

services:
  promtail:
    image: grafana/promtail:2.7.1
    volumes:
      - ./config.yaml:/etc/promtail/config.yaml:ro
      - //var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - loki-network

networks:
  loki-network: