version: '2.4'

services:
  prodenv-jenkins:
    image: generaltao725/prodenv-jenkins
    container_name:  prodenv-jenkins
    networks: 
      jenkins:
        aliases:
          - prodenv-jenkins
    environment:
      - DOCKER_HOST=tcp://prodenv-jenkins-dind:2375
    ports:
      - 8080:8080
      - 50000:50000
    volumes: 
      - prodenv-jenkins-data:/var/jenkins_home

volumes:
  prodenv-jenkins-data:

networks:
  jenkins: