version: '2.4'

services:
  jenkins:
    image: generaltao725/jenkins
    networks: 
      jenkins:
        aliases:
          - jenkins
    environment:
      DOCKER_HOST: tcp://jenkins-dind:2375
      UID: 1000
      GID: 1000
    ports:
      - 8080:8080
      - 50000:50000
    volumes: 
      - jenkins-data:/var/jenkins_home

volumes:
  jenkins-data:

networks:
  jenkins: