version: '2.4'

services:
  portainer:
    image: portainer/portainer-ce:2.19.0
    ports:
      # - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    # labels:
    #   - io.docksal.virtual-host=portainer.*
    #   - io.docksal.virtual-port=9000
