version: '2.4'

services:
  portainer:
    image: portainer/portainer-ce:2.19.0
    ports:
      - 127.0.0.1:9003:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
