version: '2.4'

services:
  jenkins-dind:
    image: docker:24.0.6-dind
    privileged: true
    command: ["--tls=false"]
    networks: 
      jenkins:
        aliases:
          - jenkins-dind
    environment:
      DOCKER_TLS_CERTDIR: ""
      # Improve performance with overlayfs.
      DOCKER_DRIVER: overlay2
      UID: 1000
      GID: 1000
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-dind-volumes:/var/lib/docker
    healthcheck:
      test: docker ps || exit 1
      interval: 10s
      timeout: 10s
      retries: 3

volumes:
  jenkins-data:

networks:
  jenkins: