version: '2.4'

services:
  prodenv-jenkins-dind:
    image: docker:dind
    container_name: prodenv-jenkins-dind
    privileged: true
    command: ["--tls=false"]
    networks: 
      jenkins:
        aliases:
          - prodenv-jenkins-dind
    environment:
      DOCKER_TLS_CERTDIR: ""
      # Improve performance with overlayfs.
      DOCKER_DRIVER: overlay2
    healthcheck:
      test: docker ps || exit 1
      interval: 10s
      timeout: 10s
      retries: 3

volumes:
  prodenv-jenkins-data:

networks:
  jenkins: