version: '2.4'

services:
  prodenv-mc:
    image: minio/mc:RELEASE.2023-02-16T19-20-11Z
    container_name: prodenv-mc
    env_file:
     - ../.env
    entrypoint: 
      - sh
      - -c
      - /shared/entrypoint.sh
    volumes:
     - prodenv-mc-data:/backup
     - ./shared:/shared
    networks:
      - loki-network
    labels:
      - "docker-volume-backup.archive-pre=/bin/bash -c 'mc mirror --remove --overwrite minio/loki-data /backup/current'"
      - "command-runner.group=prodenv"
      - "command-runner.shell=/bin/sh -c"
      - "command-runner.command=mc mirror --overwrite /backup/archived minio/loki-data; rm -r /backup/archived"


networks:
  loki-network:

values:
 prodenv-mc-data: