services:
  ddns:
    image: favonia/cloudflare-ddns:1.17.0
    network_mode: host
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges:true
    env_file:
     - .env
    environment:
      - DOMAINS=taonity.org,*.taonity.org
      - PROXIED=true
