services:
  db:
    restart: unless-stopped
    ports:
      - 5436:5432

  flyway:
    restart: "no"

  backend:
    restart: unless-stopped

  frontend:
    restart: unless-stopped
    ports:
      - 127.0.0.1:3004:3000