version: '2.4'

services:
  prodenv-loki:
    image: grafana/loki:2.7.1
    container_name: prodenv-loki
    volumes:
      - ./configs:/etc/loki
    command: "-config.file=/etc/loki/config.yaml -config.expand-env=true"
    env_file:
     - ../.env
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - loki-network

networks:
  loki-network: