version: '2.4'

services:
  loki:
    image: grafana/loki:3.5.2
    volumes:
      - ./configs:/etc/loki
    command: "-config.file=/etc/loki/config.yaml -config.expand-env=true"
    env_file:
     - ../.env
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3
