services:
  loki:
    image: grafana/loki:3.6.9
    restart: unless-stopped
    volumes:
      - ./configs:/etc/loki
    command: "-config.file=/etc/loki/config.yaml -config.expand-env=true"
    env_file:
     - ../.env
    healthcheck:
      test: [ "CMD", "/usr/bin/loki", "-health" ]
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 3
