version: '2.4'

services:
  minio:
    image: minio/minio:RELEASE.2023-02-17T17-52-43Z
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler && \
        minio server /data --console-address ":9002"
    environment:
      - MINIO_ROOT_USER=loki
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    env_file:
     - ../.env
    ports:
      - 9002:9002
    volumes:
      - minio-data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 1s
      timeout: 1s
      retries: 3
    networks:
      - loki-network

values:
  minio-data:

networks:
  loki-network: