name: Run Integration Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Run Tests
        working-directory: ./test
        run: |
          ./test.sh
